# [Bracket Spacing]
# Print spaces between brackets in object literals.
bracketSpacing: true
# [Bracket Line]
# Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element
# at the end of the last line instead of being alone on the next line
# (does not apply to self-closing elements).
bracketSameLine: false
# [Print Width]
# Specify the line length that the printer will wrap on.
printWidth: 120
# [Semicolons]
# Print semicolons at the ends of statements.
semi: true
# [Single Attribute Per Line]
# Enforce single attribute per line in HTML, Vue and JSX.
singleAttributePerLine: true
# [Quotes]
# Use single quotes instead of double quotes.
singleQuote: false
# [Tab Width]
# Specify the number of spaces per indentation-level.
tabWidth: 2
# [Trailing Commas]
# "es5" - Trailing commas where valid in ES5 (objects, arrays, etc.).
# No trailing commas in type parameters in TypeScript.
trailingComma: es5

overrides:
  - files:
      - "*.htm"
      - "*.html"
    options:
      singleAttributePerLine: false
